version: "3.7"

services:
  app:
    build: .
    container_name: swiftfiddle-lsp
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 8080:8080
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    restart: always
