apiVersion: v1
kind: Service
metadata:
  name: lang-server
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "lang-server-backendconfig"}}'
spec:
  selector:
    app.kubernetes.io/name: lang-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: lang-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lang-server
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 150m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lang-server
  labels:
    app.kubernetes.io/name: lang-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lang-server
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lang-server
      annotations:
        commit_sha: "%COMMIT_SHA%"
    spec:
      nodeSelector:
        name: defaultpool
      containers:
        - image: swiftfiddle.azurecr.io/swiftfiddle/lang-server:latest
          name: lang-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          resources:
            limits:
              cpu: 200m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 512Mi
      terminationGracePeriodSeconds: 60
