name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  REGISTRY_NAME: swiftfiddle.azurecr.io
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  CLUSTER_NAME: swiftfiddle
  CLUSTER_RESOURCE_GROUP: swiftfiddle
  APP_NAME: swiftfiddle/lang-server
  SERVICE_NAME: lang-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - uses: azure/setup-kubectl@v3
      - uses: azure/aks-set-context@v3
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Build and Push Container
        run: |
          set -ex

          IMAGE_TAG=${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest

          docker build --rm --tag ${IMAGE_TAG} .
          docker push ${IMAGE_TAG}

      - name: Deploy
        run: |
          set -ex

          sed "s/%COMMIT_SHA%/${{ github.sha }}/g;" "k8s/pod_template.yaml" | kubectl apply -f -

          kubectl rollout status deployment/${{ env.SERVICE_NAME }}
          kubectl get services -o wide
